
package com.anonysm.tranglo.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EPin_ReloadSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EPinReloadSoap {


    /**
     * 
     * @param userID
     * @param transID
     * @param prodCode
     * @param deno
     * @param destNo
     * @param sourceNo
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Request_Reload", action = "http://tempuri.org/Request_Reload")
    @WebResult(name = "Request_ReloadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Request_Reload", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestReload")
    @ResponseWrapper(localName = "Request_ReloadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestReloadResponse")
    public String requestReload(
        @WebParam(name = "sourceNo", targetNamespace = "http://tempuri.org/")
        String sourceNo,
        @WebParam(name = "destNo", targetNamespace = "http://tempuri.org/")
        String destNo,
        @WebParam(name = "prodCode", targetNamespace = "http://tempuri.org/")
        String prodCode,
        @WebParam(name = "deno", targetNamespace = "http://tempuri.org/")
        int deno,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "transID", targetNamespace = "http://tempuri.org/")
        String transID);

    /**
     * 
     * @param userID
     * @param transID
     * @param prodCode
     * @param deno
     * @param destNo
     * @param sourceNo
     * @param password
     * @return
     *     returns org.tempuri.RequestReloadAmountResponse.RequestReloadAmountResult
     */
    @WebMethod(operationName = "Request_ReloadAmount", action = "http://tempuri.org/Request_ReloadAmount")
    @WebResult(name = "Request_ReloadAmountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Request_ReloadAmount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestReloadAmount")
    @ResponseWrapper(localName = "Request_ReloadAmountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestReloadAmountResponse")
    public com.anonysm.tranglo.service.RequestReloadAmountResponse.RequestReloadAmountResult requestReloadAmount(
        @WebParam(name = "sourceNo", targetNamespace = "http://tempuri.org/")
        String sourceNo,
        @WebParam(name = "destNo", targetNamespace = "http://tempuri.org/")
        String destNo,
        @WebParam(name = "prodCode", targetNamespace = "http://tempuri.org/")
        String prodCode,
        @WebParam(name = "deno", targetNamespace = "http://tempuri.org/")
        int deno,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "transID", targetNamespace = "http://tempuri.org/")
        String transID);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PingResponse")
    public int ping();

    /**
     * 
     * @param userID
     * @param transID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Transaction_Inquiry", action = "http://tempuri.org/Transaction_Inquiry")
    @WebResult(name = "Transaction_InquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Transaction_Inquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransactionInquiry")
    @ResponseWrapper(localName = "Transaction_InquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransactionInquiryResponse")
    public String transactionInquiry(
        @WebParam(name = "transID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param userID
     * @param transID
     * @param password
     * @return
     *     returns org.tempuri.TransactionInquiryDetailsResponse.TransactionInquiryDetailsResult
     */
    @WebMethod(operationName = "Transaction_Inquiry_Details", action = "http://tempuri.org/Transaction_Inquiry_Details")
    @WebResult(name = "Transaction_Inquiry_DetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Transaction_Inquiry_Details", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransactionInquiryDetails")
    @ResponseWrapper(localName = "Transaction_Inquiry_DetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransactionInquiryDetailsResponse")
    public com.anonysm.tranglo.service.TransactionInquiryDetailsResponse.TransactionInquiryDetailsResult transactionInquiryDetails(
        @WebParam(name = "transID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param userID
     * @param transID
     * @param password
     * @return
     *     returns org.tempuri.EWalletInquiryResponse.EWalletInquiryResult
     */
    @WebMethod(operationName = "EWallet_Inquiry", action = "http://tempuri.org/EWallet_Inquiry")
    @WebResult(name = "EWallet_InquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EWallet_Inquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EWalletInquiry")
    @ResponseWrapper(localName = "EWallet_InquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EWalletInquiryResponse")
    public com.anonysm.tranglo.service.EWalletInquiryResponse.EWalletInquiryResult eWalletInquiry(
        @WebParam(name = "transID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param userID
     * @param transID
     * @param prodCode
     * @param deno
     * @param password
     * @return
     *     returns org.tempuri.ProductPriceInquiryResponse.ProductPriceInquiryResult
     */
    @WebMethod(operationName = "Product_Price_Inquiry", action = "http://tempuri.org/Product_Price_Inquiry")
    @WebResult(name = "Product_Price_InquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Product_Price_Inquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductPriceInquiry")
    @ResponseWrapper(localName = "Product_Price_InquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductPriceInquiryResponse")
    public com.anonysm.tranglo.service.ProductPriceInquiryResponse.ProductPriceInquiryResult productPriceInquiry(
        @WebParam(name = "transID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "prodCode", targetNamespace = "http://tempuri.org/")
        String prodCode,
        @WebParam(name = "deno", targetNamespace = "http://tempuri.org/")
        String deno);

}
