/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JListChooser.java
 *
 * Created on Sep 23, 2010, 3:10:30 PM
 */

package com.anosym.utitlities.swing;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.List;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Luffy
 */
public class JListChooser<T> extends javax.swing.JDialog {

    /** Creates new form JListChooser */
    public JListChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //set to centre
        SwingFramework.toCentre(this);
    }
    private List<T> list;
    public static final String PROP_LIST = "list";
    private List<T> listChoices;
    public static final String PROP_LISTCHOICES = "listChoices";

    /**
     * Get the value of listChoices
     *
     * @return the value of listChoices
     */
    public List<T> getListChoices() {
        return listChoices;
    }

    /**
     * Set the value of listChoices
     *
     * @param listChoices new value of listChoices
     */
    public void setListChoices(List<T> listChoices) {
        List<T> oldListChoices = this.listChoices;
        this.listChoices = listChoices;
        propertyChangeSupport.firePropertyChange(PROP_LISTCHOICES, oldListChoices, listChoices);
    }
    private T listChoice;
    public static final String PROP_LISTCHOICE = "listChoice";

    /**
     * Get the value of listChoice
     *
     * @return the value of listChoice
     */
    public T getListChoice() {
        return listChoice;
    }

    /**
     * Set the value of listChoice
     *
     * @param listChoice new value of listChoice
     */
    public void setListChoice(T listChoice) {
        T oldListChoice = this.listChoice;
        this.listChoice = listChoice;
        propertyChangeSupport.firePropertyChange(PROP_LISTCHOICE, oldListChoice, listChoice);
    }

    /**
     * Get the value of list
     *
     * @return the value of list
     */
    public List<T> getList() {
        return list;
    }

    /**
     * Set the value of list
     *
     * @param list new value of list
     */
    public void setList(List<T> list) {
        List<T> oldList = this.list;
        this.list = list;
        propertyChangeSupport.firePropertyChange(PROP_LIST, oldList, list);
    }
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("List:"));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${list}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jList1);
        bindingGroup.addBinding(jListBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${listChoice}"), jList1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${listChoices}"), jList1, org.jdesktop.beansbinding.BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.listChoice = null;
        this.listChoices = null;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public static<T> T getChoice(List<T> list, String title){
        JListChooser<T> dialog = new JListChooser(new javax.swing.JFrame(), true);
        dialog.setTitle(title);
        dialog.setList(list);
        dialog.setVisible(true);
        dialog.jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        return dialog.listChoice;
    }

    public static<T> List<T> getChoices(List<T> list, String title){
        JListChooser<T> dialog = new JListChooser(new javax.swing.JFrame(), true);
        dialog.setTitle(title);
        dialog.setList(list);
        dialog.setVisible(true);
        return dialog.listChoices;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
